### ISSUE TITLE
Gracefully handle non-inline config object

### ISSUE THREAD

**Issue by rwjblue** [srvance/ember-cli-build-config-editor#3]
I noticed this stack trace while perusing #-ember-cli channel in community slack, and figured I could report here with some details.

The default pattern of `ember-cli-build.js` is well tested:

```js
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
  });

  return app.toTree();
});
```

However, some users move the config to a stand alone object like:

```js
module.exports = function(defaults) {
  var config = {
    'some-things': { enabled: true }
  };
  var app = new EmberApp(defaults, config);

  return app.toTree();
});
```

Doing the above throws an error:

```
$ ember generate ember-bootstrap
installing ember-bootstrap
Installing for Bootstrap 3 using preprocessor sass
  install package bootstrap-sass
NPM: Installed bootstrap-sass@^3.3.7
Added import statement to app/styles/app.scss
Added ember-bootstrap configuration to ember-cli-build.js
Cannot read property 'properties' of undefined
TypeError: Cannot read property 'properties' of undefined
    at EmberBuildConfigEditor.findOrAddConfigKey (~/projects/expel-ember/node_modules/ember-cli-build-config-editor/lib/build-config-editor.js:52:36)
    at EmberBuildConfigEditor.edit (~/projects/expel-ember/node_modules/ember-cli-build-config-editor/lib/build-config-editor.js:95:40)
    at Class.addBuildConfiguration (~/projects/expel-ember/node_modules/ember-bootstrap/blueprints/ember-bootstrap/index.js:193:28)
    at adjustBootstrapDependencies.then.then.then (~/projects/expel-ember/node_modules/ember-bootstrap/blueprints/ember-bootstrap/index.js:73:24)
    at tryCatch (~/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (~/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (~/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (~/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

---

As a general rule, it seems good to handle any errors during parsing/updating and leave the `ember-cli-build.js` untouched, but print a detailed message to the console with what the user _should_ add/change manually to their `ember-cli-build.js`. Something like:

```
Could not automatically update `ember-cli-build.js`. Please add the following configuration manually:

  var app = new EmberApp(defaults, {
    'ember-bootstrap': {
      stuff: 'here'
    }
  });
```

**Comment by simonihmig** [comment]
@rwjblue thanks for taking the time analyze and report this, I think this identifies the problem very precisely!

**Comment by srvance** [comment]
Thank you @rwjblue. The first issue on the repo is so well written!

**Comment by srvance** [comment]
v0.3.1 handles sensible error behavior that let's the consumer manage the response. I'm going to leave this open for a more general fix that attempts to edit the separated config.
